### ISSUE TITLE
Consider adding mode (of operation) parameter

### ISSUE THREAD

**Issue by MichaelCotton** [NTIA/SCOS-Transfer-Spec#20]
Mode of operation could specify: 
(1) Manual control/data download of standalone sensor
(2) Manager control/data distro of distributed sensors

Possibly others...

Likely different metadata requirements for different modes. Schedule_entry object, for example, is not required for (1) but is required for (2). In (2), schedule_entry object would allow data client subscription via schedule entry.

**Comment by bradeales** [comment]
Solved by making Schedule_entry object "required".
