### ISSUE TITLE
Disclaimer/licensing statement needed

### ISSUE THREAD

**Issue by lsegreNTIA** [NTIA/SCOS-Transfer-Spec#22]
It is important to identify whether data is in the public domain and/or whether there are restrictions on its use. It  might be necessary to have two fields: one a public domain/restricted use Y/N identifier, and one that holds a longer explanation of restrictions or requirements.

**Comment by bradeales** [comment]
Core SigMF namespace has a 'License' field. Our name space has an additional 'Data Sensitivty' field. These two fields fulfill this requirement.
