### ISSUE TITLE
Clarify horizontal_gain_pattern and vertical_gain_pattern in Antenna Object

### ISSUE THREAD

**Issue by jhazentia** [NTIA/SCOS-Transfer-Spec#3]
As a casual reader of the SCOS-Transfer-Spec, it was not clear to me how these two fields should be implemented. Should it be an array of just the gain values (assuming 0-359 degree order for each element in the array), or should it be an array of objects with each object containing the degree and the gain value. Would the units for elevation and azimuth be in degrees?

**Comment by jhazentia** [comment]
@MichaelCotton

**Comment by MichaelCotton** [comment]
I think it is a fine idea to be a bit more specific, e.g., description of horizontal_gain_pattern is Antenna gain pattern in horizontal plane from 0 to 359 degrees in 1 degree steps. Alternatively, we could be less restrictive and have metadata for angle and gain, but I kind-uv like the 1-degree step approach.

**Comment by MichaelCotton** [comment]
@djanderson can you update since it is only in description?

**Comment by MichaelCotton** [comment]
Resolved in mean-power-detection merge
https://github.com/NTIA/sigmf-ns-scos/pull/12
