### ISSUE TITLE
Type of `array` is not specific enough

### ISSUE THREAD

**Issue by djanderson** [NTIA/SCOS-Transfer-Spec#6]
When trying to implement objects such as the Antenna object, describing fields like the `horizontal_gain_pattern` as an "array" type is not specific enough. In this case, I assume it should be "array of floats", but that should be explicit (as well as all other cases of type: "array").

**Comment by MichaelCotton** [comment]
horizontal_gain_patter: array of floats
vertical_gain_pattern: array of floats
rf_path_specs: array of RFPath objects
calibrations: array of cal_data objects (cal_data object needs definition)

**Comment by MichaelCotton** [comment]
My opinion: the SignalConditioningUnit object should be comprised of
        rf_path array of rf_path_spec objects 
instead of
        rf_path_specs array of RFPath objects

**Comment by MichaelCotton** [comment]
Resolved by mean-power-detection merge
https://github.com/NTIA/sigmf-ns-scos/pull/12
