### ISSUE TITLE
DataExtractionUnit's max_power unit

### ISSUE THREAD

**Issue by djanderson** [NTIA/SCOS-Transfer-Spec#7]
[DataExtractionUnit](https://github.com/NTIA/SCOS-Transfer-Spec#dataextractionunit-object)['max_power'] unit is listed as `dB`, but seems like this should be in `dBm`. Is that correct?

**Comment by MichaelCotton** [comment]
Yes, 'dBm' are the correct units.

**Comment by djanderson** [comment]
Duplicate of issue #4.
